apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: gitopslearning-dev
  namespace: gitopslearning-dev
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:dev-*
spec:
  releaseName: gitopslearningDev
  chart:
    git: git@github.com:gcavalcante8808/gitOpsLearning
    path: charts/gitopslearning
    ref: master
  values:
    image:
      repository: gcavalcante8808/gitopslearning
      tag:dev-1
    replicaCount: 2
